---
- name: debug statement
  debug:
    msg: "ansible_system: {{ ansible_system }},     build_location: {{ splunk.build_location }}"

- name: check for existing files
  find:
    paths: /opt

- name: Download Splunk source (Linux)
  get_url:
    url: "{{ splunk.build_location }}"
    dest: "{{ splunk.opt }}"
    mode: 0777
    timeout: 600
  register: item
  until: item | succeeded
  retries: 5
  delay: 10
  when:
  - splunk.build_location | regex_search("^(http).*")
  - ansible_system is match("Linux")

- name: Download Splunk source (Windows)
  get_url:
    url: "{{ splunk.build_location }}"
    dest: "{{ splunk.opt }}"
    mode: 0777
    timeout: 600
  register: item
  until: item | succeeded
  retries: 5
  delay: 10
  when:
  - splunk.build_location | regex_search("^(http).*")
  - ansible_system is match("CYGWIN*|Win32NT")

- name: check for new files
  find:
    paths: /opt