---
- name: Download splunk package
  get_url:
    url: "{{ splunk.build_location }}"
    dest: "/tmp/splunk.tgz"
    mode: 0777
    timeout: 600
    force: true
  register: item
  until: item | succeeded
  retries: 5
  delay: 10
  when:
  - splunk.build_location | regex_search("^(http).*")
  - not splunk.dynamic
  - ansible_system is match("CYGWIN*|Win32NT")

- name: Install Splunk (Linux)
  unarchive:
    src: "/tmp/splunk.tgz"
    dest: "{{ splunk.opt }}"
    owner: "{{ splunk.user }}"
    group: "{{ splunk.group }}"
    remote_src: "{{ splunk.build_remote_src }}"
  when: ansible_system is match("Linux")
  register: result
  until: result is succeeded
  retries: "{{ retry_num }}"
  delay: 3

- name: Install Splunk (Windows)
  command: "msiexec /I /tmp/splunk.tgz AGREETOLICENSE=yes LAUNCHSPLUNK=0 INSTALLDIR=C:\\\\opt\\\\splunk /passive /qn"
  when: ansible_system is match("CYGWIN*|Win32NT")
  register: result
  until: result is succeeded
  retries: "{{ retry_num }}"
  delay: 3

- name: Remove installer
  file:
    dest: "/tmp/splunk.tgz"
    state: "absent"
  ignore_errors: yes
  become: yes
  become_method: sudo
  become_user: root
