---
- name: Dynamic mode, download Splunk package
  include_tasks: dynamic_splunk_install.yml
  when: splunk.dynamic | bool

- name: Install Splunk
  unarchive:
    src: "{{ splunk.build_destination }}"
    dest: "{{ splunk.opt }}"
    owner: "{{ splunk.user }}"
    group: "{{ splunk.group }}"
    remote_src: "{{ splunk.build_remote_src }}"
  when: ansible_system is match("Linux")
  register: result
  until: result is succeeded
  retries: "{{ retry_num }}"
  delay: 3

- name: Install Splunk (Windows)
  command: "msiexec /I {{ splunk.build_destination }} AGREETOLICENSE=yes LAUNCHSPLUNK=0 INSTALLDIR=C:\\\\opt\\\\splunk /passive /qn"
  when: ansible_system is match("CYGWIN*|Win32NT")
  register: result
  until: result is succeeded
  retries: "{{ retry_num }}"
  delay: 3

- name: Remove installer
  file:
    dest: "{{ splunk.build_destination }}"
    state: "absent"
  ignore_errors: yes
  become: yes
  become_method: sudo
  become_user: root
