---
- name: Dynamic mode, download Splunk package
  include_tasks: dynamic_splunk_install.yml
  when:
  - splunk.dynamic | bool
  - ansible_system is match("CYGWIN*|Win32NT")

- name: Install Splunk (Linux)
  unarchive:
    src: "/tmp/splunk.tgz"
    dest: "{{ splunk.opt }}"
    owner: "{{ splunk.user }}"
    group: "{{ splunk.group }}"
    remote_src: "{{ splunk.build_remote_src }}"
  when: ansible_system is match("Linux")
  register: result
  until: result is succeeded
  retries: "{{ retry_num }}"
  delay: 3

- name: Install Splunk (Windows)
  command: "msiexec /I /tmp/splunk.tgz AGREETOLICENSE=yes LAUNCHSPLUNK=0 INSTALLDIR=C:\\\\opt\\\\splunk /passive /qn"
  when: ansible_system is match("CYGWIN*|Win32NT")
  register: result
  until: result is succeeded
  retries: "{{ retry_num }}"
  delay: 3

- name: Remove installer
  file:
    dest: "/tmp/splunk.tgz"
    state: "absent"
  ignore_errors: yes
  become: yes
  become_method: sudo
  become_user: root
