---
- include_tasks: ../../../roles/splunk_common/tasks/find_installed_apps.yml

# TODO: Might be better to use synchronize here, but we'll need rsync installed
- name: Copy installed apps to deployment-apps
  command: "cp -R {{ splunk.app_paths.default }}/{{ item }} {{ splunk.app_paths.deployment }}"
  register: copy_apps
  changed_when: copy_apps.rc == 0
  failed_when: copy_apps.rc != 0
  become: yes
  become_user: "{{ splunk.user }}"
  with_items: "{{ installed_apps }}"
